[[redirects]]
  from = "https://csharpfritz.livecoders.dev"
  to = "https://twitch.tv/csharpfritz"
  status = 301
  force = false

[[redirects]]
  from = "/"
  to = "https://twitch.tv/team/livecoders"
  status = 301
  force = false
	
