[[redirects]]
  from = "https://join.livecoders.dev"
  to = "https://github.com/livecoders/Home/issues/new?assignees=csharpfritz&labels=application&template=application.md&title=Application+for+Membership"
  status = 301
  force = false
  
[[redirects]]
  from = "https://csharpfritz.livecoders.dev"
  to = "https://twitch.tv/csharpfritz"
  status = 301
  force = false

[[redirects]]
  from = "https://jitterted.livecoders.dev"
  to = "https://twitch.tv/jitterted"
  status = 301
  force = false

[[redirects]]
  from = "https://luckynos7evin.livecoders.dev"
  to = "https://twitch.tv/luckynos7evin"
  status = 301
  force = false

[[redirects]]
  from = "https://seekaplayer.livecoders.dev"
  to = "https://twitch.tv/seekaplayer"
  status = 301
  force = false

[[redirects]]
  from = "https://codebasealpha.livecoders.dev"
  to = "https://twitch.tv/codebasealpha"
  status = 301
  force = false

[[redirects]]
  from = "https://ramblinggeek.livecoders.dev"
  to = "https://twitch.tv/ramblinggeek"
  status = 301
  force = false

[[redirects]]
  from = "https://notmyself.livecoders.dev"
  to = "https://twitch.tv/iamnotmyself"
  status = 301
  force = false

[[redirects]]
  from = "https://baldbeardedbuilder.livecoders.dev"
  to = "https://twitch.tv/baldbeardedbuilder"
  status = 301
  force = false

[[redirects]]
  from = "/"
  to = "https://twitch.tv/team/livecoders"
  status = 301
  force = false
	
