[[redirects]]
  from = "/"
  to = "https://twitch.tv/team/livecoders"
  status = 301
  force = false
	
[[redirects]]
  from = "https://*.livecoders.dev"
  to = "https://twitch.tv/:splat"
  status = 301
  force = false

